# Numpy Arrays

In [1]:
import numpy as np

In [2]:
oneDArray = np.array([1,2,3,4,5])
print(oneDArray)

[1 2 3 4 5]


In [4]:
print(oneDArray.ndim) #dimension

1


In [5]:
twoDArray = np.array([[1,2,3], [5,6,7]])
print(twoDArray)

[[1 2 3]
 [5 6 7]]


In [6]:
print(twoDArray.ndim)

2


In [7]:
threeDArray = np.array([[[1,2,3], [5,6,7]], [[2,7,8], [-9,-8,-6]]])
print(threeDArray)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 2  7  8]
  [-9 -8 -6]]]


In [9]:
print(threeDArray.ndim)

3


In [11]:
twoDArray = np.array([[1,2,3], [5,6,7]])
print(twoDArray.shape) #rows and columns

(2, 3)


# Zeros

In [12]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
zerosArray = zerosArray.astype(int)
print(zerosArray)

[0 0 0 0 0 0 0 0 0 0]


# Ones

In [14]:
onesArray = np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
onesArray = onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


# Full

In [16]:
preFilledArray = np.full(10,5)
print(preFilledArray)

[5 5 5 5 5 5 5 5 5 5]


# Statistics

In [17]:
matrix1 = np.array([[1,2,3], [4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [18]:
np.min(matrix1)

1

In [19]:
np.max(matrix1)

6

In [20]:
np.sum(matrix1)

21

In [21]:
np.mean(matrix1)

3.5

In [22]:
np.std(matrix1)

1.707825127659933

In [23]:
np.median(matrix1)

3.5